# Generated by Django 4.1.1 on 2022-09-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('account', models.CharField(max_length=12)),
                ('payment', models.CharField(max_length=12)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UaeTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('cnic', models.CharField(max_length=12)),
                ('passport', models.CharField(max_length=1243)),
                ('payment', models.CharField(max_length=1243)),
                ('account', models.CharField(max_length=1243)),
                ('place', models.CharField(max_length=1243)),
                ('image', models.ImageField(default='', upload_to='')),
                ('date', models.DateField()),
            ],
        ),
    ]
